ARG AVTOOLS_BASE_IMAGE=avtools-utils:cpu
FROM ${AVTOOLS_BASE_IMAGE}

ARG BAKE_WD14_ASSETS=1
ARG WARM_MODELS=1

RUN if [ "$BAKE_WD14_ASSETS" = "1" ]; then /bin/sh /usr/local/bin/fetch-wd14-assets /opt/wd14-models/wd14-convnextv2.v1; fi
RUN if [ "$WARM_MODELS" = "1" ]; then /usr/local/bin/warm-models; fi
